apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: crossplane-system
  source:
    path: ''
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.6.2
    helm:
      valueFiles:
        - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system 
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
