apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-helloworld
  namespace: argocd
spec:
  project: helloworld
  source:
    repoURL: 'git@github.com:laetho/decops.git'
    targetRevision: HEAD
    path: bootstrap/ 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
