apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealed-secrets 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Bitnami Sealed Secrets 
  sourceRepos:
    - 'git@github.com:laetho/decops.git'
  destinations:
    - namespace: '*' 
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

